version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_NAME=ICMS - Integrated Clinic Management System
      - VITE_APP_VERSION=1.0.0
    restart: unless-stopped
